name: mern app
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.3
        
      - name: install dependecy
        run: npm install

      - name: create build
        run: npm run build

      - name: deploy
        run: echo "hi its deploying"
      
      
  
